name: DreamSkillBar
version: 1.1.0
main: com.killercraft.jimy.ILandSkillBar
author: StartDream-kylin
commands:
  iland:
    description: This is a command that is used by DreamSkillBar
depend:
  - SkillAPI
  - PlaceholderAPI
  - GermPlugin